# Generated by Django 3.2.8 on 2021-10-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_posts_xyz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='xyz',
        ),
    ]
