# Generated by Django 3.2.8 on 2021-11-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_posts_xyz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
